### ISSUE TITLE
Add OTP 21.0 Support

### ISSUE THREAD

**Issue by walkr** [hansihe/rustler#158]
Rustler doesn't compile with the latest OTP release.

**Comment by mischov** [comment]
If it's anything like the usual problem, it's that erlang_nif-sys won't be working, which would line up with the fact that erlang_nif-sys just did an update and release for OTP 21.

**Comment by scrogson** [comment]
I've created this PR: https://github.com/hansihe/rustler/pull/159

There is currently a segfault that needs to be addressed.

**Comment by scrogson** [comment]
Fixed on `master`

**Comment by walkr** [comment]
I still get compile errors on my machine (macOS, 2017 MacBook).

`cargo build` inside the native lib's folder results in 

```
...

"_enif_get_tuple", referenced from:
    rustler::wrapper::nif_interface::enif_get_tuple::h2d48e9a899c2d3df in librustler-fa3e925b94083a41.rlib(rustler-fa3e925b94083a41.rustler11.rcgu.o)
"_enif_make_badarg", referenced from:
    rustler::wrapper::nif_interface::enif_make_badarg::habebd816e293c64b in librustler-fa3e925b94083a41.rlib(rustler-fa3e925b94083a41.rustler11.rcgu.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
I'm compiling my [forked rox](https://github.com/walkr/rox) when I get this.

What am I doing wrong?

**Comment by scrogson** [comment]
NIFs built with Rustler are compiled with the mix compiler. So `mix compile` should compile everything appropriately.

**Comment by walkr** [comment]
Indeed. It works now! Thank you!
