### ISSUE TITLE
Tiny memory leak in `rustler_export_nifs`

### ISSUE THREAD

**Issue by jorendorff** [hansihe/Rustler#53]
```rust
                name: ::std::ffi::CString::new($name).unwrap().into_raw() as *const u8,
```

I don't think this is safe; I think the `CString` is freed at the end of the statement.

Maybe we can do this instead:

```rust
    name: concat!($name, "\x00").as_bytes() as *const u8,
```

**Comment by hansihe** [comment]
CString::into_raw transfers ownership, so it is safe in that sense.

The way it's done currently does cause the string to leak however, so your suggestion is probably a better idea here

**Comment by jorendorff** [comment]
OK, db0cf3b is the fix for this.

**Comment by goertzenator** [comment]
@hansihe Is this completely leak free now?  If so I'd like to retract https://github.com/erlang/otp/pull/1294 which has technical problems that I did not foresee.  Upcoming Rust macro features in the next year or 2 should resolve the Rust-side limitations I experienced.

**Comment by hansihe** [comment]
@goertzenator No, it is still not completely leak free. The leak is not very large however, and it only happens on a NIF unload,  so we are probably fine either way. You decide if you want to retract the PR.

**Comment by jorendorff** [comment]
@hansihe Where do we still leak memory?

**Comment by hansihe** [comment]
@jorendorff Isn't [this](https://github.com/hansihe/Rustler/blob/3ba023a223ef1e2ce6af467e178a9a0074eed024/src/export.rs#L51) leaking memory? There is nothing dropping that.

**Comment by goertzenator** [comment]
`entry` gets moved into `NIF_ENTRY` which is static.  I've looked closely at this file and I'm not seeing leaks.

**Comment by hansihe** [comment]
@goertzenator Ah, I forgot how static variables worked for a second. There is indeed no leaks.
